language: cpp
compiler: gcc

cache:
  directories:
    - opencv/

dist: trusty
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

jobs:
 include:
  - stage: OpenCV
    install:
      - sudo apt-get install build-essential
      - sudo apt-get install libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
    before_script:
      - bash build_opencv.sh
      - cd opencv/build/
      - sudo make install
      - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
      - sudo ldconfig
      
      - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
      - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
      - export CC=/usr/bin/gcc-7
      - export CXX=/usr/bin/g++-7
      - gcc -v && g++ -v
      - cd ../../
      - cd OpenCV_practice/OpenCV_practice
    script:
      - cmake .
      - make
  - stage: Qt
    install: 
      - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
      - sudo apt-get update
      - sudo apt-get install qt5-qmake qt510base qt510script qt510declarative qt510tools qt510x11extras qt510svg qt510quickcontrols2
      - source /opt/qt510/bin/qt510-env.sh
    before_script:
      - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
      - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
      - export CC=/usr/bin/gcc-7
      - export CXX=/usr/bin/g++-7
      - gcc -v && g++ -v
      - cd ChessVisualizer
    script:
      - /opt/qt510/bin/qmake
      - make
