language: cpp
compiler: gcc

dist: trusty
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

jobs:
 include:
  - stage: Qt
    install: 
      - sudo apt-get update
      - sudo apt-get install qt5-qmake
    before_script:
      - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
      - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
      - export CC=/usr/bin/gcc-7
      - export CXX=/usr/bin/g++-7
      - gcc -v && g++ -v
      - cd Qt
    script:
      - qmake -project -Wall 
      - qmake -makefile -Wall ToyProject.pro
      - make