language: cpp
compiler: gcc

cache:
  directories:
    - opencv/

dist: trusty
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

jobs:
 include:
  - stage: OpenCV
    install:
      - sudo apt-get install build-essential
      - sudo apt-get install libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
    before_script:
      - bash shell/build_opencv.sh
      - cd opencv/build/
      - sudo make install
      - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
      - sudo ldconfig
      - echo "OpenCV installed."
      
      - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
      - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
      - export CC=/usr/bin/gcc-7
      - export CXX=/usr/bin/g++-7
      - gcc -v && g++ -v
      - cd ../../
      - cd OpenCV_practice/OpenCV_practice
    script:
      - cmake .
      - make
  - stage: Qt
    install: 
      - sudo apt-get update
      - sudo apt-get install qt5-qmake
    before_script:
      - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
      - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
      - export CC=/usr/bin/gcc-7
      - export CXX=/usr/bin/g++-7
      - gcc -v && g++ -v
      - cd ChessVisualizer
    script:
      - qmake -project -Wall 
      - qmake -makefile -Wall ChessVisualizer.pro
      - make